import jkLiquid from "../pages/images/jkl.png";
import Liquid2 from "../pages/images/liquid2.png";
import HandWash from "../pages/images/handWash.png";

export const SlidesItems = [
  {
    id: 1,
    img: Liquid2,
    title: "LIQUID DETERGENTS",
    desc: "DON'T COMPROMISE ON CLEANING! GET FLAT 20% FOR NEW USERS",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
    bg: "f5fafd",
    height: "100%",
  },
  {
    id: 2,
    img: HandWash,
    title: "HANDWASH COLLECTION",
    desc: "DON'T COMPROMISE ON CLEANING! GET FLAT 20% FOR NEW USERS",
    bg: "fcf1ed",
    height: "100%",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 3,
    img: jkLiquid,
    title: "DISH WASHERS",
    desc: "DON'T COMPROMISE ON CLEANING! GET FLAT 20% FOR NEW USERS",
    height: "100%",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
];

export const categories = [
  {
    id: 4,
    img: Liquid2,
    title: "LIQUID DETERGENT",
    detail: "Clean beyond measure with our liquid treasure",
    price: 200,
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 5,
    img: Liquid2,
    title: "HANDWASH COLLECTION!",
    detail: "Clean hands, happy heart - with every wash",
    price: 150,
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 6,
    img: Liquid2,
    title: "DISH WASHER",
    detail:
      "Let your dishwasher do the dirty work - for sparkling clean dishes every time",
    price: 80,
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 7,
    img: Liquid2,
    title: "TOILET CLEANER",
    detail: "Powerful cleaning for a refreshing, hygienic throne",
    price: 80,
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 8,
    img: Liquid2,
    title: "FLOOR CLEANER",
    detail: "Step into a spotless world - with every sweep, mop and swirl",
    price: 60,
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
];

export const popularProducts = [
  {
    id: 9,
    img: Liquid2,
    type: "detergent",
    title: "Liquid Detergent",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 12,
    img: Liquid2,
    type: "handWash",
    title: "Hand Wash",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 13,
    img: Liquid2,
    type: "handWash",
    title: "Hand Wash",
    size: "500 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 14,
    img: Liquid2,
    type: "toiletCleaner",
    title: "Floor Cleaner",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 15,
    img: Liquid2,
    type: "floorCleaner",
    title: "Floor Cleaner",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 16,
    img: Liquid2,
    type: "floorCleaner",
    title: "Floor Cleaner",
    size: "500 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 17,
    img: Liquid2,
    type: "dishWasher",
    title: "Dish Washer",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 19,
    img: Liquid2,
    type: "dishWasher",
    title: "Dish Washer",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 20,
    img: Liquid2,
    type: "washingSoap",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 21,
    img: Liquid2,
    type: "washingSoap",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 22,
    img: Liquid2,
    type: "bathingSoap",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 23,
    img: Liquid2,
    type: "bathingSoap",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 23,
    img: Liquid2,
    type: "handWash",
    size: "500 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
  {
    id: 24,
    img: Liquid2,
    type: "bathingSoap",
    size: "100 ml",
    productDescription:
      "PROTECT EVERY FIBER, PREVENT COLOUR FADING IN FABRIC, IT DOES NOT FADE COLOURS INFACT IT INCREASES THE LIFE OF THE FABRIC AS IT ACT AS CONDITIONER, REMOVE STAIN BETTER THAN POWDER, MADE FOR ALL FABRICS WOOLEN ,COTTON ETC",
  },
];
